# Generated by Django 4.0.3 on 2022-04-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='label',
        ),
    ]
